#!/bin/bash

source .fonctions

CLEAN_SETUP () {
	echo ""
}
TRAP_ON

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN

app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

CHECK_VAR "$app" "app name not set"

CHECK_USER "$admin"

CHECK_PATH

sudo yunohost app setting $app domain -v $domain
sudo yunohost app setting $app path -v $path
sudo yunohost app setting $app admin -v $admin

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/telegram.conf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting telegram skipped_uris -v "/"
sudo yunohost app ssowatconf