#!/bin/bash
# This restore script is adapted to Yunohost >=2.5

# Exit on command errors and treat unset variables as an error
set -eu

# Source app helpers
source /usr/share/yunohost/helpers

# The parameter $app is the id of the app instance ex: ynhexample__2
app=$YNH_APP_INSTANCE_NAME

# Get old parameter of the app
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "${app}" \
    || ynh_die "Path not available: ${domain}${path}"

# Check $final_path
final_path="/opt/${app}"
if [ -d "${final_path}" ]; then
	ynh_die "There is already a directory: ${final_path}"
fi

# Check configuration files nginx
nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
if [ -f "${nginx_conf}" ]; then
	ynh_die "The NGINX configuration already exists at '${nginx_conf}'. 
	You should safely delete it before restoring this app."
fi

# Create system user dedicace for this app
ynh_system_user_create $app

 # Restore sources & data
sudo cp -a ./sources "${final_path}"

# Set permissions
sudo chown -R $app: "${final_path}"

# Restore nginx configuration files
sudo cp -a ./nginx.conf   "${nginx_conf}"

# Reload services
sudo systemctl reload nginx
sudo yunohost app ssowatconf